comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: ywxt/blog-comment # [在此输入仓库]
    data-repo-id: R_kgDOJU1Mhw # [在此输入仓库 ID]
    data-category: Announcements # [在此输入分类名]
    data-category-id: DIC_kwDOJU1Mh84CVqav
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous
    